/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Common;
import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import Stud.*;
import Teacher.*;
/**
 *
 * @author Abhay Goyal
 */
public class logged extends javax.swing.JFrame {

    /**
     * Creates new form logged
     */
    public static String name;
    public static String email;
    public static void getNumber(String name1)//this method is giving a department of user
    {
        name=name1;
    }
    
    public String setNumber()
    {
        return name;
    }
    
    public static void getEmail(String em)//this method gives the emailid of the user 
    {
        email=em;
    }
    
    public String setEmail()
    {
        return email;
    }    
    
    public logged() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Email-ID");

        jLabel2.setText("Password");

        jButton1.setText("Next--->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Student");

        jRadioButton2.setText("Teacher");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(80, 80, 80)
                                .addComponent(jRadioButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(jTextField1))))))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Statement stmt;
    public void connect()
    {
        try {
             Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/portal","root","abhay");
            stmt=con.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        connect();String pass;
        pass=String.valueOf(jPasswordField1.getPassword());
        if(jTextField1.getText().isEmpty()|| pass.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter the details");
            return;
        }
        if(!(jRadioButton1.isSelected() || jRadioButton2.isSelected()) )
        {
            JOptionPane.showMessageDialog(this,"Enter the the type");
            return;
        }
        String name=jTextField1.getText();String c;
        getEmail(name);
        //String pass=jPasswordField1.getPassword();
        if(jRadioButton1.isSelected())
            c="s";
        else
            c="t";
        logged l=new logged();
        String s1="Select email,password,type from login;";
        //JOptionPane.showMessageDialog(this, s1);
        try
        {
            ResultSet rs=stmt.executeQuery(s1);
            while(rs.next())
            {
                String em=rs.getString(1);
                String pa=rs.getString(2);
                String ty=rs.getString(3);
                if((em.equals(name)) && (pa.equals(pass) && ty.equals(c)))
                {
                    JOptionPane.showMessageDialog(this,"Welcome");
                    this.setVisible(false);
                    l.observe(ty);
                    break;
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Wrong username or password");
                    System.exit(0);
                    //break;
                    //return;
                }
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
        //SELECT CASE WHEN name='Abhay' and email='Aaybh' THEN "TRUE" ELSE "FALSE" END as Saleable,email FROM login;

    }//GEN-LAST:event_jButton1ActionPerformed

    public void observe(String type)
    {
       if(jRadioButton1.isSelected())
       {
           JOptionPane.showMessageDialog(this,"1. Enter qs\n2.See the qs entered");
           Scanner sc=new Scanner(System.in);
           int ch=sc.nextInt();
           switch(ch)
           {
               case 1:
                   detailsqs qs=new detailsqs();
                   qs.setVisible(true);
                   this.setVisible(false);
               case 2:
                   
           }
       }
        
       
       if(jRadioButton2.isSelected())
       {
           String s1="Select dept from login where type='"+type+"';";
           JOptionPane.showMessageDialog(this, s1);
           connect();String dept="";
           try
           {
               ResultSet rs=stmt.executeQuery(s1);
               while(rs.next())
               {
                   dept=rs.getString(1);
               }
               getNumber(dept);
           }
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(this, e.getMessage());
           }
       }
    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logged().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
